FROM openjdk:11
ADD target/PensionerDetailMicroservice-0.0.1-SNAPSHOT.jar PensionerDetailMicroservice-0.0.1-SNAPSHOT.jar

#EXPOSE 8080
ENTRYPOINT ["java", "-jar","PensionerDetailMicroservice-0.0.1-SNAPSHOT.jar"]
